import type { SiteData } from '@/types/content'

// Fallback / seed content. Used when Sanity is not configured yet (or a
// document is missing), and imported into Sanity by scripts/seed-sanity.ts.
//
// Confirmed by the client (4 Oct 2026): name, logo, address, hours, phones.
// Everything else is marked `verified: false` or kept behind a feature flag.
// See docs/PROJECT_PLAN.md §16.4 for the placeholder register.

export const fallbackData: SiteData = {
  source: 'fallback',
  settings: {
    name: 'Sri Shakti Sweets',
    localName: 'ಶ್ರೀ ಶಕ್ತಿ ಸ್ವೀಟ್ಸ್',
    tagline: 'Sweets, Snacks & Cakes',
    description:
      'Sri Shakti Sweets: sweets, snacks and cakes from our shops in Okalipuram and on Magadi Road, Bengaluru. Open daily 8 am – 10 pm. Call or WhatsApp.',
    mainShopName: 'Okalipuram',
    address: {
      line1: '23/1-1, Sri Shakti Tower, Ground Floor',
      line2: '1st Main Rd',
      locality: 'Okalipuram',
      city: 'Bengaluru',
      state: 'Karnataka',
      postalCode: '560021',
      country: 'IN',
    },
    landmark: 'Near Majestic',
    phones: [
      { number: '+919341222517', display: '+91 93412 22517', label: 'Mobile' },
      { number: '+918023121869', display: '+91 80 2312 1869', label: 'Shop' },
    ],
    branches: [
      {
        // Second shop — supplied by the client (4 Oct 2026). Same hours as the main shop; no Google Maps listing.
        name: 'Magadi Road',
        address: {
          line1: '38/4, Sardar Complex',
          line2: "7th 'A' Cross, Magadi Road",
          locality: 'Near Anjan Theatre',
          city: 'Bengaluru',
          state: 'Karnataka',
          postalCode: '560023',
          country: 'IN',
        },
        landmark: 'Near Anjan Theatre',
        phones: [{ number: '+917406600747', display: '+91 74066 00747' }],
        sameHoursAsMain: true,
      },
    ],
    // WhatsApp number confirmed by the client (4 Oct 2026); used for both shops.
    whatsapp: '919341222517',
    email: 'srishaktisweets@yahoo.in',
    googleMapsUrl: 'https://share.google/pt83rt9uZGji7Nte7',
    social: {},
    features: {
      gifting: false,
      whyUs: true,
      reviews: false,
      gallery: true,
      prices: false,
      kannadaAccents: true,
    },
  },

  hours: {
    week: [0, 1, 2, 3, 4, 5, 6].map((day) => ({ day, closed: false, open: '08:00', close: '22:00' })),
    special: [],
  },

  copy: {
    heroEyebrow: 'Sweets · Snacks · Cakes · Bengaluru',
    heroHeadline: 'A little sweetness. A lot of *joy*.',
    heroSubline:
      'Sweets, snacks and cakes from our shops in Okalipuram and on Magadi Road. Open every day, 8 am to 10 pm.',
    heroImage: {
      src: '/images/demo/hero-shop-display.jpg',
      alt: 'Sri Shakti Sweets display: samosas, mixture, motichoor laddus, barfi, gulab jamun, a chocolate cake and a strawberry cream cake on brass and wooden stands',
      width: 1374,
      height: 1145,
      // Supplied by the client; marked representative until confirmed as a real photo of the shop.
      representative: true,
      lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAARABQDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAQFA//EACQQAAICAAYABwAAAAAAAAAAAAECAAMEBRESEzEiMjM0QVFx/8QAGAEAAgMAAAAAAAAAAAAAAAAAAQQAAgP/xAAYEQADAQEAAAAAAAAAAAAAAAAAAQIxEv/aAAwDAQACEQMRAD8A0MrvtJYWvoT0TO9+Ip5RU+IXf9TBap2u3cjBR8g9zlja6ksTE7yXXsGIzbxjzhIoxNC87+IHUxJTmrWHdqg1iTlhLafSMhzL27/kRDOFaMCryCIiaPQLD//Z',
    },
    introLine:
      'Two neighbourhood sweet shops near Majestic. Drop by for something sweet, or message us before your next celebration.',
    sweetsEyebrow: 'From our counter',
    sweetsTitle: 'Counter *favourites*',
    sweetsIntro: 'A few favourites from both shops. See the full menu for everything on our counter.',
    visitTitle: 'Come *say hello*',
    finalCtaTitle: 'Celebrating something? Let’s make it *sweeter*.',
    whatsappGeneral: 'Hi Sri Shakti Sweets! I found you on your website and would like to know more.',
    whatsappProduct: 'Hi! I’d like to know about {product}. Is it available today, and what is the price?',
    whatsappBulk:
      'Hi! I’m planning {occasion} and need sweets in bulk.\nApprox. quantity: \nDate needed: \nPlease share options.',
  },

  // Categories and products. Sources (4 Oct 2026):
  //  - Zomato menu for Sri Shakti Sweets: Doodh/Kesar/Choco Peda, Horlicks Burfi, Mota Sev, Cream Bell ice creams
  //  - Client's photos: Kaju Katli, Motichoor Laddu, Gulab Jamun, Rasmalai, Malai Sandwich
  //  - Client's message: snacks (om pudi, pakoda, mixture, special mixture), cakes (butterscotch, black forest, pineapple, blueberry, black currant, fruit) and
  //    biscuits (milk, coconut, salt, rusks). Both shops stock the same range.
  categories: [
    {
      slug: 'sweets',
      title: 'Sweets',
      description: 'Mysore pak, pedas, burfis, laddus, jamuns and milk sweets.',
      art: 'katli',
      // LICENCE NEEDED before launch: Getty preview supplied by the client, cropped to the platter
      // (original in assets-src/client-provided/sweets-platter.jpg; see docs/PROJECT_PLAN.md §8.5).
      image: {
        src: '/images/categories/sweets.jpg',
        alt: 'A platter of assorted sweets: pista rolls, fruit-shaped sweets, silver-leaf barfis and almond burfi',
        width: 332,
        height: 415,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAUABADASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAQP/xAAlEAACAQMEAQQDAAAAAAAAAAABAgMABCEFERIxcRMiUWEzQYH/xAAVAQEBAAAAAAAAAAAAAAAAAAAEAf/EABsRAAIDAAMAAAAAAAAAAAAAAAABAhExEhNB/9oADAMBAAIRAxEAPwBS91O+1V3kW6aG3A3VEVtgPI7PyTiutvqNxpxMsd2JYEHugYluXgnIxU7jyjcur7/jRpEx1nA6P6pt2428gkmVfUTZQSCXx9H7oSj48EypYUtSsY/WMsbyRP8AKNsD/Oq2wtVYqZJJZADgO24HgUUUTlLq0tKz/9k=',
      },
    },
    {
      slug: 'snacks',
      title: 'Snacks',
      description: 'Chaats, om pudi, pakoda, mixtures and sev.',
      art: 'namkeen',
      image: {
        src: '/images/categories/snacks.jpg',
        alt: 'Bowls of samosas, sev, mixture, banana chips and other savoury snacks',
        width: 828,
        height: 941,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAASABADASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAMBAgQF/8QAIBAAAgICAQUBAAAAAAAAAAAAAQIAAxIxEQQhIiRRQf/EABUBAQEAAAAAAAAAAAAAAAAAAAMF/8QAFxEBAQEBAAAAAAAAAAAAAAAAAQAhQf/aAAwDAQACEQMRAD8AhCUva4jjiJ6tK7wbi47iUtQ1HKyzNONAxdL03ghjgqjX2S9NqCHblWu2S+R39mkD2QPzHUIRyNv/2Q==',
      },
    },
    {
      slug: 'cakes',
      title: 'Cakes',
      description: 'Butterscotch, black forest, pineapple and fruit cakes.',
      art: 'cake',
      image: {
        src: '/images/categories/cakes.jpg',
        alt: 'Cream cakes with strawberries, a red velvet cake, a mango cake and a chocolate cake',
        width: 828,
        height: 941,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAASABADASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAEEAwX/xAAgEAACAgICAgMAAAAAAAAAAAABAgADBBEFEhMhQVFx/8QAFgEBAQEAAAAAAAAAAAAAAAAABAID/8QAGREAAwEBAQAAAAAAAAAAAAAAAAECMREh/9oADAMBAAIRAxEAPwBWYj4psUrtNe/cy4vTrYK1Ndf2fmc/kHy6AGZ3sVxFg8jkVYrIB0TcDUPng5UsLd9sUdvf7JyB4HGhCE0eELT/2Q==',
      },
    },
    {
      slug: 'biscuits',
      title: 'Biscuits & Rusks',
      description: 'Milk, coconut and salt biscuits, and crisp rusks.',
      art: 'biscuit',
      image: {
        src: '/images/categories/biscuits.jpg',
        alt: 'Square biscuits in a basket, sliced rusks, jam-centre cookies, nut cookies and two-tone biscuits on a counter',
        width: 1536,
        height: 1024,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAALABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAgT/xAAjEAACAgEDAwUAAAAAAAAAAAABAwIRBAAFIRIxQRMiUXGh/8QAFAEBAAAAAAAAAAAAAAAAAAAABP/EABgRAQEAAwAAAAAAAAAAAAAAAAEAETFR/9oADAMBAAIRAxEAPwCXITFbYLNnqJoBftlffnQXiJkmSzjmxzcgLjx2BB/frRw2TzNymnIkZrBvpJoHnz86u3ZK0LX6UBCzZrzoQOszlOX/2Q==',
      },
    },
    {
      slug: 'ice-creams',
      title: 'Ice Creams',
      description: 'Cream Bell kulfis, cones, cups and bars.',
      art: 'icecream',
      image: {
        src: '/images/categories/ice-creams.jpg',
        alt: 'Trays of strawberry, chocolate, mango and pistachio ice cream in a counter, with sundaes and waffle cones',
        width: 1536,
        height: 1024,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAALABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwH/xAAgEAACAgICAgMAAAAAAAAAAAABAgMRBCEABRIiMVFx/8QAFAEBAAAAAAAAAAAAAAAAAAAABP/EABYRAQEBAAAAAAAAAAAAAAAAAAEAEf/aAAwDAQACEQMRAD8ACXFOO6vLKaVPEEe33qq4ceMixhhPG8b+2gfw64/azSDJVA1KaJA1yZKCLtREliMqtrevkcIDL0v/2Q==',
      },
    },
  ],

  // `featured` items appear on the home page; everything appears on /menu.
  products: [
    // Sweets
    {
      slug: 'malai-sandwich',
      name: "Malai Sandwich",
      category: 'sweets',
      description: "Soft chhena rounds filled with sweet cream and topped with silver leaf.",
      image: {
        src: '/images/products/malai-sandwich.jpg',
        alt: 'Three malai sandwich sweets with a saffron cream filling, silver leaf and a cherry',
        width: 1400,
        height: 2037,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAXABADASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIDBf/EABwQAQEBAAMBAQEAAAAAAAAAAAECAAMRIRIiMf/EABYBAQEBAAAAAAAAAAAAAAAAAAECBf/EABkRAQEBAAMAAAAAAAAAAAAAAAEAAhESQf/aAAwDAQACEQMRAD8A2S833jk6rkZEB8HTYoWZ/bJ71pd5Hi0hrx8kdMlJ/FywPHSj64xjqewBf//Z',
      },
      art: 'sandwich',
      tags: [],
      featured: true,
      verified: true,
    },
    {
      slug: 'kaju-katli',
      name: "Kaju Katli",
      category: 'sweets',
      description: "Thin cashew diamonds, finished with a sheet of silver leaf.",
      // LICENCE NEEDED before launch: iStock/Getty preview supplied by the client (see docs/PROJECT_PLAN.md §8.5).
      image: {
        src: '/images/products/kaju-katli.jpg',
        alt: 'Kaju katli diamonds with silver leaf arranged in a star on a plate, with cashews',
        width: 612,
        height: 393,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAKABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQIE/8QAHRAAAgICAwEAAAAAAAAAAAAAAQMCEQBBEyE0cf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAWEQEBAQAAAAAAAAAAAAAAAAABACH/2gAMAwEAAhEDEQA/AEEvUbMqvV5TXI4jZjGWu8Id55HeYFSkWiyT9OEHJSbf/9k=',
      },
      art: 'katli',
      tags: [],
      featured: true,
      verified: true,
    },
    {
      slug: 'motichoor-laddu',
      name: "Motichoor Laddu",
      category: 'sweets',
      description: "Tiny pearls of boondi pressed into soft, fragrant laddus.",
      // LICENCE NEEDED before launch: Getty preview supplied by the client (see docs/PROJECT_PLAN.md §8.5).
      image: {
        src: '/images/products/motichoor-laddu.jpg',
        alt: 'Orange motichoor laddus on a brass plate, with a lit clay diya behind',
        width: 408,
        height: 612,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAYABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAUA/8QAJBAAAgICAQMEAwAAAAAAAAAAAQIDBAARMRIhUQUTFEFxcpH/xAAWAQEBAQAAAAAAAAAAAAAAAAAEAAL/xAAbEQEAAgMBAQAAAAAAAAAAAAACAAEREiEDBP/aAAwDAQACEQMRAD8Ai2RDVREhjKAAEkRBmY/t4/mTbUiSMZFh9oeN842vU9QnjjKTBUfZAZ+APv8AGDvVJUkLCQzIOX1rWEKO2M9jUXY2o8lOxeiRIIYzuAaDAHpPPfA3LiNI3x1VVbt0r33mzZHxNXNr6XYxP//Z',
      },
      art: 'laddu',
      tags: [],
      featured: true,
      verified: true,
    },
    {
      slug: 'gulab-jamun',
      name: "Gulab Jamun",
      category: 'sweets',
      description: "Soft, golden-brown dumplings soaked in warm sugar syrup.",
      // LICENCE NEEDED before launch: Getty preview supplied by the client (see docs/PROJECT_PLAN.md §8.5).
      image: {
        src: '/images/products/gulab-jamun.jpg',
        alt: 'Gulab jamuns in syrup topped with slivered almonds, in a white plate',
        width: 612,
        height: 408,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAALABADASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAEF/8QAIBAAAgIBBAMBAAAAAAAAAAAAAQIDBBEABRIhFEFRUv/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAZEQACAwEAAAAAAAAAAAAAAAAAARIhIkH/2gAMAwEAAhEDEQA/ANHbYUhpPLDVWecYGXAPEfcH5oG52j4DWpascDiRFQKpUSq2eiP0MZ61I7M1ch4ZGRiTkj3o7yPdvtJadpmjU8OZyF69DRuWOg1pH//Z',
      },
      art: 'jamun',
      tags: [],
      featured: true,
      verified: true,
    },
    {
      slug: 'rasmalai',
      name: "Rasmalai",
      category: 'sweets',
      description: "Delicate discs resting in chilled saffron milk with pistachio.",
      // LICENCE NEEDED before launch: Getty preview supplied by the client (see docs/PROJECT_PLAN.md §8.5).
      image: {
        src: '/images/products/rasmalai.jpg',
        alt: 'Rasmalai in saffron milk with pistachio and saffron strands, in a blue bowl',
        width: 612,
        height: 408,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAALABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAwb/xAAhEAACAgIBBAMAAAAAAAAAAAABAgMRAAQFEyFRYRJB4f/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAGxEAAQQDAAAAAAAAAAAAAAAAEQABAhITIVH/2gAMAwEAAhEDEQA/AKbkZD1YYzI0UTfIsymiartf1+YWnsKkvTErMjIWAdrKke/GPtqskDq4sAWPR85P8RbbcjsWZj2tiSavJvCWSx1xJgAF/9k=',
      },
      art: 'rasmalai',
      tags: [],
      featured: true,
      verified: true,
    },
    {
      slug: 'doodh-peda',
      name: "Doodh Peda",
      category: 'sweets',
      description: "Rich, melt-in-the-mouth milk peda.",
      art: 'peda',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'kesar-peda',
      name: "Kesar Peda",
      category: 'sweets',
      description: "Milk peda flavoured with saffron.",
      art: 'peda',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'choco-peda',
      name: "Choco Peda",
      category: 'sweets',
      description: "Milk peda with chocolate.",
      art: 'peda',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'horlicks-burfi',
      name: "Horlicks Burfi",
      category: 'sweets',
      description: "Creamy malted burfi that melts effortlessly.",
      art: 'katli',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'chandrakala',
      name: "Chandrakala",
      category: 'sweets',
      description: "Soft shell with a rich, fragrant filling.",
      art: 'generic',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'boondi',
      name: "Boondi",
      category: 'sweets',
      description: "Tiny, crisp sweet pearls, a joyful classic.",
      art: 'laddu',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'badusha',
      name: "Badusha",
      category: 'sweets',
      description: "Crispy golden pastry with a syrup-soaked centre.",
      art: 'generic',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'pineapple-burfi',
      name: "Pineapple Burfi",
      category: 'sweets',
      description: "Tropical, aromatic and sweet in every bite.",
      art: 'katli',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'coconut-burfi',
      name: "Coconut Burfi",
      category: 'sweets',
      description: "Fresh, fragrant coconut burfi.",
      art: 'katli',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'soan-papdi',
      name: "Soan Papdi",
      category: 'sweets',
      description: "Flaky, melt-in-the-mouth festive classic.",
      art: 'katli',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'ghee-laddu',
      name: "Ghee Laddu",
      category: 'sweets',
      description: "Buttery laddus with a rich ghee aroma.",
      art: 'laddu',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'mysore-pak',
      name: "Mysore Pak",
      category: 'sweets',
      description: "Karnataka's pride: desi ghee, gram flour and cardamom.",
      art: 'katli',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'cashewnut-coffee-roll',
      name: "Cashewnut Coffee Roll",
      category: 'sweets',
      description: "Coffee and cashew, blended in every bite.",
      art: 'generic',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'dry-fruit-chikki',
      name: "Dry Fruit Chikki",
      category: 'sweets',
      description: "Crunchy nuts in sweet, golden brittle.",
      art: 'katli',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'kaju-pan',
      name: "Kaju Pan",
      category: 'sweets',
      description: "Paan-shaped cashew indulgence.",
      art: 'generic',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'chocolate-roll',
      name: "Chocolate Roll",
      category: 'sweets',
      description: "Creamy chocolate milk roll.",
      art: 'generic',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'milk-cake',
      name: "Milk Cake",
      category: 'sweets',
      description: "Sweet, velvety milk cake with a rich texture.",
      art: 'katli',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'rossy-peda',
      name: "Rossy Peda",
      category: 'sweets',
      description: "Soft, creamy morsels with a delicate sweetness.",
      art: 'peda',
      tags: [],
      featured: false,
      verified: true,
    },
    // Snacks
    {
      slug: 'mota-sev',
      name: "Mota Sev",
      category: 'snacks',
      description: "Thick, crunchy gram-flour sev.",
      image: {
        src: '/images/products/mota-sev.jpg',
        alt: 'A heap of crunchy mota sev with peanuts and curry leaves in a steel tray',
        width: 765,
        height: 1024,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAAWABADASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAUBAgME/8QAIxAAAgEEAgEFAQAAAAAAAAAAAQIDAAQREiExURMiMmFxkf/EABYBAQEBAAAAAAAAAAAAAAAAAAUCA//EAB0RAAICAQUAAAAAAAAAAAAAAAACAQMhERITFCL/2gAMAwEAAhEDEQA/AJa3iX1FiiYs/wAihOGPPeTSwWDS7Brd1I4yzY/lM1lMisdSqEEKCBkj88fVUUI9voDtHngk45HeDRXYaBHhUzEMlmrtFOzKeNHGwGfHiuNLq4S1m2ZQVk19gwOu6KK0qneurZJs8zg//9k=',
      },
      art: 'namkeen',
      tags: [],
      featured: true,
      verified: true,
    },
    {
      slug: 'om-pudi',
      name: "Om Pudi",
      category: 'snacks',
      description: "Fine, crisp gram-flour sev (omapodi).",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'pakoda',
      name: "Pakoda",
      category: 'snacks',
      description: "Crunchy, spiced fried pakoda.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'mixture',
      name: "Mixture",
      category: 'snacks',
      description: "Classic savoury mixture.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'special-mixture',
      name: "Special Mixture",
      category: 'snacks',
      description: "Our special mixture. Ask us what's in today's batch.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'masala-puri',
      name: "Masala Puri",
      category: 'snacks',
      description: "Crispy puris, green peas, special masala, onions and sev.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'pani-puri',
      name: "Pani Puri",
      category: 'snacks',
      description: "Delhi-style golgappas with sweet and spicy waters.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'bhel-puri',
      name: "Bhel Puri",
      category: 'snacks',
      description: "Puffed rice, sev, potato and tangy chutneys.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'sev-puri',
      name: "Sev Puri",
      category: 'snacks',
      description: "Crispy discs topped with a tangy medley.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'dahi-puri',
      name: "Dahi Puri",
      category: 'snacks',
      description: "Crisp puris with churned curd and sweet-spicy chutneys.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'aloo-puri',
      name: "Aloo Puri",
      category: 'snacks',
      description: "Crisp textures with vibrant, balanced flavours.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'samosa-chat',
      name: "Samosa Chat",
      category: 'snacks',
      description: "Crushed samosa with onion, tomato, curd and more.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'kachori-chat',
      name: "Kachori Chat",
      category: 'snacks',
      description: "Kachori with spicy chole, yogurt and chutneys.",
      art: 'namkeen',
      tags: [],
      featured: false,
      verified: true,
    },
    // Cakes
    {
      slug: 'butterscotch-cake',
      name: "Butterscotch Cake",
      category: 'cakes',
      image: {
        src: '/images/products/butterscotch-cake.jpg',
        alt: 'Butterscotch cake with caramel drip, cream rosettes, praline crunch and white chocolate shards',
        width: 757,
        height: 506,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAALABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAABAP/xAAkEAEAAQMDAgcAAAAAAAAAAAABAgMEEQAFIRIxIiMyQVFxsf/EABQBAQAAAAAAAAAAAAAAAAAAAAT/xAAZEQACAwEAAAAAAAAAAAAAAAABAgAREjH/2gAMAwEAAhEDEQA/ALz261JF5K0YTciEBD25iPfQr3b6MqUWhbpOPhDpAkfS8ukzWvDzFeMccfmgbnKVtYlWjJjUT1ZymfjPbQ8MpFGN0pHJ/9k=',
      },
      art: 'cake',
      tags: [],
      featured: true,
      verified: true,
    },
    {
      slug: 'black-forest-cake',
      name: "Black Forest Cake",
      category: 'cakes',
      art: 'cake',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'pineapple-cake',
      name: "Pineapple Cake",
      category: 'cakes',
      art: 'cake',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'blueberry-cake',
      name: "Blueberry Cake",
      category: 'cakes',
      art: 'cake',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'black-currant-cake',
      name: "Black Currant Cake",
      category: 'cakes',
      art: 'cake',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'fruit-cakes',
      name: "Fruit Flavour Cakes",
      category: 'cakes',
      description: "All fruit flavours. Ask us what’s available.",
      art: 'cake',
      tags: [],
      featured: false,
      verified: true,
    },
    // Biscuits
    {
      slug: 'milk-biscuits',
      name: "Milk Biscuits",
      category: 'biscuits',
      image: {
        src: '/images/products/milk-biscuits.jpg',
        alt: 'Stacks of golden square milk biscuits on a wooden tray',
        width: 757,
        height: 505,
        representative: true,
        lqip: 'data:image/jpeg;base64,/9j/2wBDABALDA4MChAODQ4SERATGCgaGBYWGDEjJR0oOjM9PDkzODdASFxOQERXRTc4UG1RV19iZ2hnPk1xeXBkeFxlZ2P/2wBDARESEhgVGC8aGi9jQjhCY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2P/wAARCAALABADASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAgT/xAAgEAADAAEDBQEAAAAAAAAAAAABAgMRAAQSBRMhQVEx/8QAFQEBAQAAAAAAAAAAAAAAAAAABAX/xAAWEQEBAQAAAAAAAAAAAAAAAAABABH/2gAMAwEAAhEDEQA/ABHp+xXst+2t4WQcnj9Oc+MY1I1YylThJyC5RWarHI+gamozbbcuIsUAJAwfWmrNEq0iUKKeJHrQMaiJf//Z',
      },
      art: 'biscuit',
      tags: [],
      featured: true,
      verified: true,
    },
    {
      slug: 'coconut-biscuits',
      name: "Coconut Biscuits",
      category: 'biscuits',
      art: 'biscuit',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'salt-biscuits',
      name: "Salt Biscuits",
      category: 'biscuits',
      art: 'biscuit',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'rusks',
      name: "Rusks",
      category: 'biscuits',
      art: 'biscuit',
      tags: [],
      featured: false,
      verified: true,
    },
    // Ice creams (Cream Bell range shown on the shop's Zomato menu)
    {
      slug: 'kulfi',
      name: "Kulfi",
      category: 'ice-creams',
      description: "Matka, kesar badam, rabri malai, pista and rajbhog kulfi.",
      art: 'icecream',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'ice-cream-cones',
      name: "Ice Cream Cones",
      category: 'ice-creams',
      description: "Chocolate, butterscotch, blackcurrant, pista and more.",
      art: 'icecream',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'ice-cream-cups',
      name: "Ice Cream Cups & Tubs",
      category: 'ice-creams',
      description: "Mango, butterscotch, French vanilla, kesar pista and more.",
      art: 'icecream',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'ice-cream-bars',
      name: "Sticks & Bars",
      category: 'ice-creams',
      description: "Choco bars, candies and ice cream sandwiches.",
      art: 'icecream',
      tags: [],
      featured: false,
      verified: true,
    },
    {
      slug: 'cassata',
      name: "Cassata",
      category: 'ice-creams',
      art: 'icecream',
      tags: [],
      featured: false,
      verified: true,
    },
  ],

  story: {
    eyebrow: 'Our shop',
    title: 'Two shops in *Bengaluru*',
    paragraphs: [
      'You’ll find Sri Shakti Sweets on the ground floor of Sri Shakti Tower in Okalipuram, a few minutes from Majestic, and at Sardar Complex on Magadi Road, near Anjan Theatre. Our counters carry sweets, snacks and cakes for everyday cravings, birthdays, guests at home and the festivals in between.',
      'Both shops are open every day from 8 am to 10 pm. Pick up a box on the way to work, or stop by for a late treat on the way home.',
    ],
    images: [],
  },

  // Only plain, confirmed facts.
  highlights: [
    { icon: 'clock', title: 'Open every day', text: '8 am to 10 pm, seven days a week.' },
    { icon: 'store', title: 'Sweets, snacks & cakes', text: 'Sweets, savouries and cakes under one roof.' },
    { icon: 'map', title: 'Two shops', text: '1st Main Rd, Okalipuram, and Magadi Road near Anjan Theatre.' },
    { icon: 'message', title: 'Order on WhatsApp', text: 'Message us to check what’s available today.' },
  ],

  // Hidden until the owner confirms gifting / bulk orders (features.gifting).
  gifting: {
    intro: 'Boxes for festivals, weddings and the office, put together at our counter.',
    occasions: [
      { title: 'Festive boxes', text: 'Assorted sweets for Deepavali, Ugadi, Sankranti and more.', art: 'katli' },
      { title: 'Weddings & functions', text: 'Bulk orders for ceremonies, return gifts and guests.', art: 'laddu' },
      { title: 'Office & bulk', text: 'Sweet boxes for teams, clients and celebrations at work.', art: 'sandwich' },
    ],
  },

  gallery: [],
  reviews: [],
}
